# Build stage
FROM golang:1.20.2-alpine3.17 AS builder
WORKDIR /app
COPY . .
RUN go build -o crawl web3/crawl/main.go

# Run stage
FROM alpine:3.17
WORKDIR /app
COPY --from=builder /app/crawl .
COPY app.env .
COPY start.sh .
COPY wait-for.sh .
COPY db/migration ./db/migration

RUN ["chmod", "+x", "/app/wait-for.sh"]
RUN ["chmod", "+x", "/app/start.sh"]

CMD [ "/app/crawl" ]
ENTRYPOINT [ "/app/start.sh" ]
