// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.17.2

package db

import ()

type Block struct {
	BlockNum   int64  `json:"block_num"`
	BlockHash  string `json:"block_hash"`
	BlockTime  int64  `json:"block_time"`
	ParentHash string `json:"parent_hash"`
}

type Log struct {
	ID        int64    `json:"id"`
	Address   string   `json:"address"`
	Topics    []string `json:"topics"`
	BlockNum  int64    `json:"block_num"`
	TxHash    string   `json:"tx_hash"`
	BlockHash string   `json:"block_hash"`
	LogIndex  int64    `json:"log_index"`
	Removed   bool     `json:"removed"`
}

type Transaction struct {
	TxHash    string `json:"tx_hash"`
	BlockHash string `json:"block_hash"`
	BlockNum  int64  `json:"block_num"`
	From      string `json:"from"`
	To        string `json:"to"`
	Nonce     int64  `json:"nonce"`
	Value     int64  `json:"value"`
	Gas       int64  `json:"gas"`
	TxIndex   int64  `json:"tx_index"`
}
