// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.17.2

package db

import (
	"context"
)

type Querier interface {
	CreateBlock(ctx context.Context, arg CreateBlockParams) (Block, error)
	CreateLog(ctx context.Context, arg CreateLogParams) (Log, error)
	CreateTransaction(ctx context.Context, arg CreateTransactionParams) (Transaction, error)
	GetBlockByHash(ctx context.Context, blockHash string) (Block, error)
	GetBlockByNumber(ctx context.Context, blockNum int64) (Block, error)
	GetFirstBlock(ctx context.Context) (Block, error)
	GetLatestBlock(ctx context.Context) (Block, error)
	GetTransactionByHash(ctx context.Context, txHash string) (Transaction, error)
	ListBlocks(ctx context.Context, arg ListBlocksParams) ([]Block, error)
	ListLogsByTransactionHash(ctx context.Context, txHash string) ([]Log, error)
	ListTransactionsByBlockHash(ctx context.Context, blockHash string) ([]Transaction, error)
	ListTransactionsByBlockNumber(ctx context.Context, blockNum int64) ([]Transaction, error)
}

var _ Querier = (*Queries)(nil)
